import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Outfit, Noto_Kufi_Arabic } from "next/font/google";
 
const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

const notoKufiArabic = Noto_Kufi_Arabic({
  subsets: ["arabic"],
  weight: ["400", "500", "700"],
  variable: "--font-arabic",
});

 
export const metadata: Metadata = {
  title: "SocailAutoCopilot",
  description: "Generated by Aerobyte Innovations app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
     className={`${outfit.variable} ${notoKufiArabic.variable}`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
